name: flutter_web_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_html: 1.2.3
  http: 0.12.2
  json_annotation: ^3.0.1
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^1.8.1
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
